
/* @pjs preload="img/bg_lose.jpg,
img/bg_play.jpg,
img/bg_start.jpg,
img/bg_win.jpg,
img/banana_angry.png,
img/banana_btn_press.png,
img/banana_btn.png,
img/banana_bullet.png,
img/banana_smile.png,
img/hami_angry.png,
img/hami_btn_press.png,
img/hami_btn.png,
img/hami_bullet.png,
img/hami_smile.png,
img/milk_01.png,
img/milk_02.png,
img/milk_03.png,
img/milk_04.png,
img/milk_05.png,
img/milk_06.png,
img/money.png";
*/
